### PR TITLE
Update QEMU version to 2.12 from Debian Buster

### PR DESCRIPTION
**Pull request by JakubVanek**
Hi,

This is my proposal to unblock https://github.com/ev3dev/docker-library/pull/4 . I have picked a newer QEMU version from here: https://packages.debian.org/buster/qemu-user-static . I have tested the executable on Debian Stretch amd64 chroot and it runs Java fine.

Thanks,
Jakub

### CODE REVIEW

**Comment by JakubVanek** [comment]
Hmmm, this is the thing that is happening: New `qemu-user-static` breaks old `binfmt-support` because it adds a new flag when installing binfmt configuration: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868030. But the flag is present only in new kernels, so upgrading the `binfmt-support` package also fails.
I will try to work it around with overwriting the old qemu package.

**Comment by JakubVanek** [comment]
This change now builds on all platforms except Debian Buster, which is broken on master as well.

**Comment by JakubVanek** [comment]
Yaay, adding `vim-tiny` to the installed packages made the package list which failed non-empty, so now even Buster build works.

**Comment by dlech** [comment]
Nice work!

Could you add some detailed explanations to the commit messages since these changes are a bit non-obvious? For example, some questions I have are... Are we just extracting the qemu-user-static package without "installing" it? Does the other package have to be `vim-tiny` or could it be any package?

**Comment by JakubVanek** [comment]
Yup, I have added a description of the issues and their solutions to each commit.

**Comment by dlech** [comment]
Thanks!

I wonder if we could get away using a required package (like `base-files`) instead of `vim-tiny`. We actually install the `vim` package in the `docker-library` repo, so this would probably result in a different version of `vim` ending up in the final product.

**Comment by JakubVanek** [comment]
I don't think that `base-files` would work - it is already in the previously installed package set. However I replaced `vim-tin` with [`ascii`](https://packages.debian.org/stretch/ascii) package now - it is small and it depends only on libc.

**Comment by dlech** [comment]
`ascii` sounds like it could be useful anyway, so very good.

**Pull request merged**
